import { Character, WorldSetting } from "./types";

export const characters: Character[] = [
  // 엘리트반
  {
    id: "hamiel",
    name: "하미엘",
    gender: "여",
    age: "비밀",
    race: "악마",
    className: "인형사",
    group: "엘리트반",
    info: "조용하지만 어딘가 4차원스러운 소녀. 눈치가 조금 없는 편이다. 평화를 추구하며, 사회에 평탄히 섞여 살고 싶어 한다. 재킷과 마스크는 좀처럼 벗는 일이 없다. 키 154cm.",
    secretInfo: "마왕군 후예. 인간인 척하고 있지만 악마다. 클래스 또한 자칭 인형사지만 실상은 네크로맨서. 조상 마왕군의 시체를 깨워 조종한다. 조상이 마왕 측에 있었기 때문에 혐오한다. 그런 그들의 시체를 이용하는 걸 일종의 조롱으로 생각하고 있는 모양이다. 실제 나이 2185.",
    physical: 40,
    defense: 66,
    magic: 40,
    squareImageUrl: "/HM_TN.webp",
    profileImageUrl: "/HM_cowboyshot.webp",
  },
  {
    id: "miki",
    name: "미키",
    gender: "남",
    age: "23",
    race: "인간",
    className: "검사",
    group: "엘리트반",
    info: "재수 없고, 남을 깔보는 성격. 엄격한 엘리트 가문의 장남이자 미야의 소꿉친구이다. 부모와 사이가 안 좋은 듯하다. 키 155cm.",
    secretInfo: "사실은 다정하고 차분한 성격. 가문의 상속을 받고 싶지 않아 가주에 부적절한 성격을 연기 중이다.",
    physical: 67,
    defense: 50,
    magic: 0,
    squareImageUrl: "/MK_TN.webp",
    profileImageUrl: "/MK_cowboyshot.webp",
  },
  {
    id: "sol",
    name: "솔",
    gender: "여",
    age: "24",
    race: "섀도우",
    className: "암살자",
    group: "엘리트반",
    info: "쿨한 누님/언니 스타일. 접촉만으로 타인의 생명력을 흡수할 수 있다. 능력 활성화/비활성화는 조절 가능. 타인의 생명력을 흡수하면서 살아가는 종족이기 때문에 전투직에 취직해 적의 생명력을 흡수하며 살려고 한다. 키 183cm.",
    physical: 60,
    defense: 30,
    magic: 25,
    squareImageUrl: "/SO_TN.webp",
    profileImageUrl: "/SO_cowboyshot.webp",
  },
  {
    id: "ventus",
    name: "벤투스",
    gender: "남",
    age: "2734",
    race: "바람 정령",
    className: "치유사",
    group: "엘리트반",
    info: "물 정령처럼 생겼지만 바람 정령. 학원의 선도부장 포지션으로, 깐깐하고 단정하다. 허점이 생기면 눈에 띄게 당황하는 편이다. 당황했을 때 상승기류가 발생하는 것은 덤이다. 키 185cm.",
    physical: 24,
    defense: 36,
    magic: 65,
    squareImageUrl: "/BT_TN.webp",
    profileImageUrl: "/BT_cowboyshot.webp",
  },
  // 상급반
  {
    id: "miya",
    name: "미야",
    gender: "여",
    age: "22",
    race: "인간",
    className: "검사",
    group: "상급반",
    info: "공손하고 예의 바르며, 겸손하기까지 하다. 낯을 가리는 편이다. 소꿉친구인 미키를 동경하여 따라잡으려고 노력하고 있다. 무언가를 부탁 받으면 거절하지 못한다. 키 170cm.",
    physical: 55,
    defense: 50,
    magic: 0,
    squareImageUrl: "/MY_TN.webp",
    profileImageUrl: "/MY_cowboyshot.webp",
  },
  {
    id: "pivot",
    name: "피벗",
    gender: "남",
    age: "45",
    race: "오토마톤",
    className: "포격수",
    group: "상급반",
    info: "유쾌하고 긍정적. 친절하지만 때로는 능청스럽다. 학원의 최고 인싸 포지션. 가끔 충전이 필요하다. 자판기 등 인격 없는 기계도 소중히 대하는 모습을 보인다. 키 190cm.",
    physical: 22,
    defense: 43,
    magic: 55,
    squareImageUrl: "/PV_TN.webp",
    profileImageUrl: "/PV_cowboyshot.webp",
  },
  {
    id: "amon",
    name: "아몬",
    gender: "남",
    age: "2371",
    race: "천족",
    className: "치유사",
    group: "상급반",
    info: "친절하고 아가페적이다. 마력 전환으로 타인 치유 및 마력 보조가 가능하다. 솔과 비슷하게 손만 닿아도 마법이 발생하지만 조절 불가능. 과회복시 대상의 몸이 망가져서 스스로 구속복으로 봉인 중이다. 키 179cm. <br/> + 프롬프트에는 안 들어간 내용이지만, 과회복으로 사람을 해친 적이 있어 타천사와 비슷한 상태가 되었다.",
    physical: 5,
    defense: 25,
    magic: 70,
    squareImageUrl: "/AM_TN.webp",
    profileImageUrl: "/AM_cowboyshot.webp",
  },
  {
    id: "jane",
    name: "제인",
    gender: "여",
    age: "21",
    race: "옥 골렘",
    className: "나이트",
    group: "상급반",
    info: "오만하고 고압적이다. 자존심이 높아서 허세를 부릴 때가 많다. 엘리트 가문의 아가씨. 미키/미야와 같은 가문은 아니다. 남들을 깔보고 다니지만 정작 자신은 겨우 상급반이라 엘리트반 얘기가 나오면 부들거린다. 키 166cm.",
    physical: 25,
    defense: 55,
    magic: 35,
    squareImageUrl: "/JY_TN.webp",
    profileImageUrl: "/JY_cowboyshot.webp",
  },
  // 중급반
  {
    id: "kelvin",
    name: "켈빈",
    gender: "남",
    age: "435",
    race: "드라고니안",
    className: "마도공학자",
    group: "중급반",
    info: "항상 피곤에 찌들어 있는 아저씨. 과거엔 화염 브레스를 이용해 화력 발전소에서 근무했으나, 에너지 발전 기술이 발달하면서 실직하고 말았다. 그 뒤로 200년째 재취업 실패 중. 반쯤 체념한 듯하다. 다른 드라고니안들을 따라 마도공학자의 길을 선택했지만 슬프게도 기계치다. 키 182cm.",
    physical: 30,
    defense: 35,
    magic: 48,
    squareImageUrl: "/KV_TN.webp",
    profileImageUrl: "/KV_cowboyshot.webp",
  },
  {
    id: "lavender",
    name: "라벤더",
    gender: "여",
    age: "76",
    race: "마녀",
    className: "마법사",
    group: "중급반",
    info: "늘 요염한 모습을 유지하며, 여유롭게 행동한다. 잘생긴 사람을 좋아해서 수작을 부릴 때가 많다. 종종 사소한 도둑질을 한다. 비싼 건 아니고 간식 정도만. 키 164cm.",
    physical: 13,
    defense: 25,
    magic: 47,
    squareImageUrl: "/LV_TN.webp",
    profileImageUrl: "/LV_cowboyshot.webp",
  },
  {
    id: "acus",
    name: "아쿠스",
    gender: "남",
    age: "불명",
    race: "리빙 아머",
    className: "랜서",
    group: "중급반",
    info: "무뚝뚝한 성격에, 사교성까지 부족해서 친구가 없다. 친구를 만들고 싶어 하지만 쉽지 않은 거 같다. 이래 봬도 최신 트렌드 마스터. 온갖 유행은 다 알고 있다. 키 187cm.",
    physical: 37,
    defense: 49,
    magic: 5,
    squareImageUrl: "/AK_TN.webp",
    profileImageUrl: "/AK_cowboyshot.webp",
  },
  {
    id: "dira",
    name: "디라",
    gender: "여",
    age: "20",
    race: "픽시",
    className: "사제",
    group: "중급반",
    info: "오지랖이 심하고 괴짜 같은 면이 있다. 사제인데, 도대체 무슨 신을 믿는 건지 저주 인형에 못을 박아 치유하는 방식을 사용한다. 게다가 주술 오타쿠 같은 면까지 가지고 있다. 키 149cm.",
    physical: 15,
    defense: 20,
    magic: 46,
    squareImageUrl: "/DR_TN.webp",
    profileImageUrl: "/DR_cowboyshot.webp",
  },
  // 초급반
  {
    id: "vivi",
    name: "비비",
    gender: "여",
    age: "21",
    race: "세이렌",
    className: "마법사",
    group: "초급반",
    info: "감정이 풍부하고, 츤데레 같은 모습을 보인다. 은근히 허당. 찐따 아닌 척하는 찐따다. 노래에 마력을 실어서 정신 교란이 가능하지만, 음치인 데다가 무대 공포증이 있어 봉인 상태나 마찬가지다. 이 때문에 기초 마법밖에 사용하지 못하고 있다. 키 158cm.",
    physical: 10,
    defense: 15,
    magic: 35,
    squareImageUrl: "/VV_TN.webp",
    profileImageUrl: "/VV_cowboyshot.webp",
  },
  {
    id: "luna",
    name: "루나",
    gender: "여",
    age: "20",
    race: "달토끼",
    className: "요리사",
    group: "초급반",
    info: "백치미 있는 순수한 소녀. 늘 발랄하게 행동한다. 요리에 치유력을 담을 수 있는데, 주로 만드는 음식은 떡. 하지만 떡 1개당 치유력이 적어서 엄청나게 많이 먹어야 한다. 배고픈 사람을 보면 참지 못한다. 잘못하면 연휴에 할머니댁에서 배고프다는 말을 했을때 일어나는 일을 겪을 수 있으니 주의. 키 157cm.",
    physical: 15,
    defense: 20,
    magic: 30,
    squareImageUrl: "/LN_TN.webp",
    profileImageUrl: "/LN_cowboyshot.webp",
  },
  {
    id: "rohi",
    name: "로히",
    gender: "남",
    age: "205",
    race: "엘프",
    className: "검방전사",
    group: "초급반",
    info: "정의롭고 늘 열정을 불태운다. 소년 만화의 노력파 주인공 성격이라고 할 수 있겠다. 용사들을 동경해서 용사 가문 사람들과 일하는 것을 목표로 하고 있다. 아직은 초심자. 키 181cm.",
    physical: 30,
    defense: 30,
    magic: 15,
    squareImageUrl: "/RH_TN.webp",
    profileImageUrl: "/RH_cowboyshot.webp",
  },
  {
    id: "jurang",
    name: "주랑",
    gender: "남",
    age: "불명",
    race: "언데드",
    className: "격투가",
    group: "초급반",
    info: "주로 멍하니 있는 시간이 많고, 느긋하게 행동한다. 무표정할 때가 많지만 의외로 따뜻하고 정이 많은 편. 타인을 챙겨주는 것을 좋아하는데, 행동이 느려서 상대를 답답하게 만들기도 한다. 키 179cm.",
    physical: 35,
    defense: 35,
    magic: 5,
    squareImageUrl: "/JR_TN.webp",
    profileImageUrl: "/JR_cowboyshot.webp",
  },
  // 교사
  {
    id: "coco",
    name: "코코",
    gender: "여",
    age: "32",
    race: "헬하운드",
    className: "버서커",
    group: "교사",
    info: "따뜻한 햇살 같은 사람. 엄마 같이 느껴지기도 한다. 이런 성격에 비해 대검을 거뜬하게 드는 힘을 가지고 있다. 귀여운 것을 보면 깨물려고 하는 버릇이 있어서 입마개를 하고 다닌다. 깨물리면 상당히 아프니까 주의하자. 헬하운드인데도 불 공포증이 있다. 키 165cm.",
    physical: 45,
    defense: 67,
    magic: 30,
    squareImageUrl: "/CC_TN.webp",
    profileImageUrl: "/CC_cowboyshot.webp",
  },
  {
    id: "typhon",
    name: "티폰",
    gender: "남",
    age: "288",
    race: "인큐버스",
    className: "거너",
    group: "교사",
    info: "뒤끝 없고 살가운 성격. 장난기가 있는 편이다. 학생들을 아끼고, 그들과 같이 노는 것을 좋아한다. 어떻게 보면 철 없는 사람 같지만, 가끔씩 은근히 어른다운 모습을 보여준다. 키 187cm.",
    physical: 66,
    defense: 44,
    magic: 25,
    squareImageUrl: "/TP_TN.webp",
    profileImageUrl: "/TP_cowboyshot.webp",
  },
  {
    id: "berry",
    name: "베리",
    gender: "여",
    age: "269",
    race: "서큐버스",
    className: "치유사",
    group: "교사",
    info: "소심하고 부끄럼이 많지만 쩔쩔매면서 할 말은 다 하는 편이다. 티폰의 친구로, 그를 따라 학원 교사로 취직했다. 긴장해서 실수하는 경우가 잦지만, 좋은 교사가 되기를 꿈꾼다. 키 161cm.",
    physical: 25,
    defense: 43,
    magic: 63,
    squareImageUrl: "/BR_TN.webp",
    profileImageUrl: "/BR_cowboyshot.webp",
  },
  {
    id: "ino",
    name: "이노",
    gender: "남",
    age: "29",
    race: "거대우주햄스터",
    className: "마법사",
    group: "교사",
    info: "학원의 설립자이자, 최장수 우주햄스터. 인간 나이로 치면 100세 넘은 할아버지다. 어려보이는 외형에 비해 꼰대스럽다. 츤데레 같은 모습도 있다. 화내도 위압감이 전혀 없어서 곤란하다.",
    physical: 40,
    defense: 40,
    magic: 71,
    squareImageUrl: "/IN_TN.webp",
    profileImageUrl: "/IN_cowboyshot.webp",
  },
];

export const worldSettings: WorldSetting[] = [
  {
    title: "연합국 수도 센트럴",
    content: [
      "다양한 종족이 모여 사는 도시. 경범죄부터 거대 재해까지 온갖 사건이 끊이지 않으나, 시민들은 이미 익숙하다.",
      "과거, 국가들이 센트럴로 통합되기 전. 용사들은 마왕을 토벌했으나 가문 대대로 내려져 오는 저주를 받고 말았다.",
      "마왕 토벌 후 기술이 급속도로 발달하였고, 계급제가 폐지된 뒤 현대화가 이루어져 지금의 센트럴이 되었다.",
      "현대화는 용사 가문의 저주들마저 자원으로 활용하기 시작했고, 저주는 더 이상 저주라고 부르기 애매한 지경에 이르렀다. 현재 대부분의 용사 가문 사람들은 공기업에서 일하는 중이다."
    ]
  },
  {
    title: "센트럴 기숙 학원",
    content: [
      "센트럴에 위치한 기숙 학원. 전투직 취업을 원하는 사람들이 취업 준비를 위해 전투를 배우러 오는 곳이다.",
      "엘리트반 / 상급반 / 중급반 / 초급반으로 나뉜다."
    ]
  },
  {
    title: "전투 시뮬레이션",
    content: [
      "학원에서 사용하는 전투 훈련용 가상공간. 특수 기기를 착용하여 입장할 수 있다. 대부분의 전투직 취업 학원에서 쓰인다.",
      "전투력을 스탯으로 수치화한 뒤 옮겨서 현실 전투를 완벽히 재현한다. 시뮬레이션 내에서는 현실 전투력과 무관하게 등록 스탯이 적용된다. 현실에서는 스탯이 100이라도 시뮬레이션 내의 스탯이 0이면 시뮬레이션에서는 스탯 0만큼의 힘만 쓸 수 있다는 뜻이다. 학원은 시뮬레이션의 스탯을 현실 전투력과 동일하게 맞추는 것을 원칙으로 걸어두었다.",
      "시뮬레이션 내부에서도 부상과 고통이 존재하지만 현실의 신체에는 영향이 없다."
    ]
  },
  {
    title: "스탯 시스템",
    content: [
      "물리력(힘·파괴력), 방어력(육체 내구도·파괴 저항), 마력(마법 파괴력·효과 강도·지속성, 또는 회복량·회복 속도)으로 나뉜다.",
      "사회에 보편화된 개념은 아니며, 전투직 취업 학원들만 사용하는 시스템이다.",
      "범위: 0~20 연약함 | ~40 일반인 | ~60 숙련자 | ~80 초인 | ~90 재해 | ~100 규격 외",
      "순수 피지컬이 부족하더라도 기교로 인해 상승할 수 있다. 예를 들면, 신체의 순수 내구도가 낮더라도 능력을 활용한 방어가 뛰어나면 방어력이 높아질 수 있다.",
      "보통의 존재는 가장 높은 스탯이 70을 넘기 힘들다. 용사 가문일 경우, 모든 스탯이 기본적으로 초인 단계를 넘는다."
    ]
  },
  {
    title: "승급 조건",
    content: [
      "엘리트반: 스탯 1개 이상 60 이상, 총합 120 이상. 바로 취직하여 현장에 투입될 수 있는 수준이다.",
      "상급반: 스탯 1개 이상 50 이상, 총합 100 이상",
      "중급반: 스탯 1개 이상 40 이상, 총합 80 이상",
      "초급반: 그 이하. 일반인이 전투를 배우러 온 수준이다."
    ]
  },
  {
    title: "유저 기본 설정",
    content: [
      "기본 시작 설정에 세팅된 유저 설정.",
      "유저는 용사 가문이며, 모든 스탯이 최대치(100)다. 용사 가문이기 때문에 저주받은 상태이다.",
      "모종의 이유로 유저는 자신의 정체와 명성이 알려지지 않은 센트럴 기숙 학원으로 편입하여 전투 시뮬레이션 스탯을 초기화했다. [이유는 창작해서 유저노트에 적으시면 좋습니다. 심심해서일 수도 있고, 다른 이유일 수도 있습니다.]",
      "시뮬레이션 스탯은 현실과 일치시키는 것이 원칙이지만, 유저는 특수 케이스로 허용 받았다. 원장인 이노만이 유저의 정체를 알고 비밀을 유지해주는 중이다.",
      "유저를 제외한 다른 용사 가문 사람들은 전부 취직한 상태이기 때문에, 학원에 유저 이외의 용사 가문 사람은 없다.",
      "최강 편입생! 기본 설정은 동일한 설정에 유저가 용사 가문이라는 설정만 빠진 시작 설정이다."
    ]
  }
];

export const schedules = [
  { date: "상시", event: "기본 일정", description: "특별한 일정이 없는 날은 오전에 전투 훈련, 오후에 이론 수업을 진행한다." },
  { date: "매주 금요일", event: "경쟁 훈련", description: "팀 결성이 가능하다. 팀과 팀이 경쟁하는 PVP식 훈련. 팀은 RPG게임의 파티 개념과 동일하다." },
  { date: "매주 토요일/일요일", event: "휴일", description: "특별한 일정이 없을 시 자유롭게 활동할 수 있다." },
  { date: "2월 28일", event: "입학식", description: "오리엔테이션과 첫 전투 시뮬레이션을 진행한다. 시뮬레이션 결과에 따라 반배정이 이루어진다." },
  { date: "3월 20일", event: "단체 봄나들이", description: "봄맞이 단체 외출." },
  { date: "4월 20일", event: "중간 모의 평가", description: "가상 재해급 토벌 실습을 진행한다." },
  { date: "5월 15일", event: "학원 교류전", description: "타 학원과의 대항전으로, 팀 결성이 가능하다." },
  { date: "6월 20일", event: "교류의 날", description: "호감이 있는 학생에게 선물을 주는 날. 발렌타인데이와 비슷하다." },
  { date: "7월 15일", event: "단체 해변 휴가", description: "2박 3일간 해변으로 단체 휴가를 떠난다." },
  { date: "8월 20일", event: "기말 모의 평가", description: "가상 기지 방어전이 진행되며 팀 결성이 가능하다." },
  { date: "9월 20일", event: "전체 경쟁 훈련", description: "배틀로얄 형식으로 진행된다." },
  { date: "10월 20일", event: "학원축제", description: "공연 및 무도회가 열린다." },
  { date: "11월 5일", event: "대축제", description: "마왕 토벌 기념일로, 전국적인 축제가 열린다." },
  { date: "12월 20일", event: "승급전", description: "교사와 1:1 대련을 통해 승급 심사를 본다." },
  { date: "12월 31일", event: "졸업식", description: "성적에 상관없이 자유 졸업이 가능하다." }
];
