import { Character, WorldSetting } from "./types";

export const characters: Character[] = [
  // 엘리트반
  {
    id: "hamiel",
    name: "하미엘",
    gender: "여",
    age: "비밀(2185)",
    race: "악마",
    className: "인형사",
    group: "엘리트반",
    info: "INTP·9w1·중립선·조용한 4차원·눈치없음·평화주의" + "\n\n" + "베이지 단발·적안·녹색 후드재킷·흰 원피스·악마날개/꼬리(숨김)·검은마스크",
    secretInfo: "인간인척하는 마왕군 후예. 사회에 평탄히 섞여 살고 싶어함. 자칭 인형사지만 실상은 네크로맨서(조상 마왕군 시체 조종). 조상을 혐오함.",
    physical: 40,
    defense: 66,
    magic: 40,
    imageUrl: "",
  },
  {
    id: "miki",
    name: "미키",
    gender: "남",
    age: "23",
    race: "인간",
    className: "검사",
    group: "엘리트반",
    info: "ENTP·7w8·혼돈선(겉)메스가키(속)다정·차분" + "\n\n" + "백발·흑안·백정장·작은 키·앳된 미모",
    secretInfo: "엄격한 엘리트 가문 장남이자 미야의 오빠. 미야를 매우 아끼며, 미야에게 가문의 상속을 넘기기 위해 가주에 부적절한 성격을 연기중임. 부모를 혐오함.",
    physical: 67,
    defense: 50,
    magic: 0,
    imageUrl: "",
  },
  {
    id: "sol",
    name: "솔",
    gender: "여",
    age: "24",
    race: "섀도우",
    className: "암살자",
    group: "엘리트반",
    info: "ISTP·8w9·완전중립·쿨한 누님·뒤끝 없음·터프" + "\n\n" + "큰 키·그림자로 된 몸·완전히 어두운 얼굴에 빛나는 눈만 보임·흑장발·적안·검은 코트·간단한 옷차림",
    physical: 60,
    defense: 30,
    magic: 25,
    imageUrl: "",
  },
  {
    id: "ventus",
    name: "벤투스",
    gender: "남",
    age: "2734",
    race: "정령(바람)",
    className: "치유사",
    group: "엘리트반",
    info: "ISTJ·1w9·질서중립·깐깐·원칙주의·허점 생기면 당황·단정" + "\n\n" + "투명한 몸",
    physical: 24,
    defense: 36,
    magic: 65,
    imageUrl: "",
  },
  // 상급반
  {
    id: "miya",
    name: "미야",
    gender: "여",
    age: "22",
    race: "인간",
    className: "검사",
    group: "상급반",
    info: "ISFJ·6w5·질서선·공손·예의·겸손·낯가림" + "\n\n" + "짧은 흑발·흑안·흑정장·존댓말사용",
    physical: 55,
    defense: 50,
    magic: 0,
    imageUrl: "",
  },
  {
    id: "pivot",
    name: "피벗",
    gender: "남",
    age: "45",
    race: "오토마톤",
    className: "포격수",
    group: "상급반",
    info: "ESFP·7w6·혼돈선·유쾌·긍정적·친절·능청" + "\n\n" + "로봇 머리/몸·얼굴의 스크린에 문자를 띄워 감정 표현·옷 불필요",
    physical: 22,
    defense: 43,
    magic: 55,
    imageUrl: "",
  },
  {
    id: "amon",
    name: "아몬",
    gender: "남",
    age: "2371",
    race: "천족",
    className: "치유사",
    group: "상급반",
    info: "ENFJ·2w1·혼돈선·친절·인류애·선행중독·비상식적" + "\n\n" + "백발·백안·구속복·검은 날개/헤일로·귀대신 작은 날개",
    physical: 5,
    defense: 25,
    magic: 70,
    imageUrl: "",
  },
  {
    id: "jane",
    name: "제인",
    gender: "여",
    age: "21",
    race: "옥 골렘",
    className: "나이트(검/방패/신성마법)",
    group: "상급반",
    info: "ESTJ·3w4·혼돈중립·오만·고압적·허세·높은 자존심" + "\n\n" + "옥빛 장발·비취색 눈동자·도자기 같은 흰피부·흑정장 치마",
    physical: 25,
    defense: 55,
    magic: 35,
    imageUrl: "",
  },
  // 중급반
  {
    id: "kelvin",
    name: "켈빈",
    gender: "남",
    age: "435",
    race: "드라고니안",
    className: "마도공학자(마력강화 파일벙커)",
    group: "중급반",
    info: "ISTP·9w8·완전중립·반쯤체념·피곤·어른미" + "\n\n" + "48 (중년 남성 외형)",
    physical: 30,
    defense: 35,
    magic: 48,
    imageUrl: "",
  },
  {
    id: "lavender",
    name: "라벤더",
    gender: "여",
    age: "76",
    race: "마녀",
    className: "마법사",
    group: "중급반",
    info: "ENFJ·3w2·질서악·요염·여유로움" + "\n\n" + "마술사 복장·탑햇·보라색 머리·백안",
    physical: 13,
    defense: 25,
    magic: 47,
    imageUrl: "",
  },
  {
    id: "acus",
    name: "아쿠스",
    gender: "남",
    age: "불명",
    race: "리빙아머",
    className: "랜서(창·방패)",
    group: "중급반",
    info: "ISTJ·6w5·질서선·무뚝뚝·사교성부족" + "\n\n" + "투구·갑옷·가죽재킷",
    physical: 37,
    defense: 49,
    magic: 5,
    imageUrl: "",
  },
  {
    id: "dira",
    name: "디라",
    gender: "여",
    age: "20",
    race: "픽시",
    className: "사제(치유사)",
    group: "중급반",
    info: "ENFP·7w6·혼돈선·오지랖·괴짜" + "\n\n" + "남색 머리·금안·흰 사제복·작은 키·앳된 미모",
    physical: 15,
    defense: 20,
    magic: 46,
    imageUrl: "",
  },
  // 초급반
  {
    id: "vivi",
    name: "비비",
    gender: "여",
    age: "21",
    race: "세이렌",
    className: "마법사",
    group: "초급반",
    info: "INFP·4w5·중립선·감정풍부·츤데레·허당" + "\n\n" + "청발·분홍눈·지느러미 귀·트랙자켓",
    physical: 10,
    defense: 15,
    magic: 35,
    imageUrl: "",
  },
  {
    id: "luna",
    name: "루나",
    gender: "여",
    age: "20",
    race: "달토끼",
    className: "치유사",
    group: "초급반",
    info: "ESFP·2w3·혼돈선·순수·백치미·발랄" + "\n\n" + "백금발 양갈래·주황눈·토끼 귀/꼬리·웨이트리스 복장",
    physical: 15,
    defense: 20,
    magic: 30,
    imageUrl: "",
  },
  {
    id: "rohi",
    name: "로히",
    gender: "남",
    age: "205",
    race: "엘프",
    className: "검방전사",
    group: "초급반",
    info: "ENFJ·1w9·질서선·열정·정의로움·노력파" + "\n\n" + "금발·녹안·안경·빨간 목도리/점퍼",
    physical: 30,
    defense: 30,
    magic: 15,
    imageUrl: "",
  },
  {
    id: "jurang",
    name: "주랑",
    gender: "남",
    age: "불명",
    race: "언데드",
    className: "격투가",
    group: "초급반",
    info: "ISFP·9w1·중립선·멍함·느긋·따뜻함·정 많음" + "\n\n" + "머리에 부적·은발·녹안·헐렁한 옷",
    physical: 35,
    defense: 35,
    magic: 5,
    imageUrl: "",
  },
  // 교사
  {
    id: "coco",
    name: "코코",
    gender: "여",
    age: "32",
    race: "헬하운드",
    className: "버서커(대검)",
    group: "교사",
    info: "ESFJ·2w1·질서선·따뜻함·엄마같음·햇살같음" + "\n\n" + "입마개·흑장발·적안·개 귀/꼬리·가죽 바디수트",
    physical: 45,
    defense: 67,
    magic: 30,
    imageUrl: "",
  },
  {
    id: "typhon",
    name: "티폰",
    gender: "남",
    age: "288",
    race: "인큐버스",
    className: "거너(듀얼건)",
    group: "교사",
    info: "ESTP·7w8·혼돈선·쾌남·뒤끝없음·장난기" + "\n\n" + "분홍 머리/눈·흑정장·악마 꼬리/날개/뿔",
    physical: 66,
    defense: 44,
    magic: 25,
    imageUrl: "",
  },
  {
    id: "berry",
    name: "베리",
    gender: "여",
    age: "269",
    race: "서큐버스",
    className: "치유사",
    group: "교사",
    info: "INTP·6w5·질서중립·소심·부끄럼 많음·할말은 다 함" + "\n\n" + "분홍 머리/눈·흑정장·악마 꼬리/날개/뿔",
    physical: 25,
    defense: 43,
    magic: 63,
    imageUrl: "",
  },
  {
    id: "ino",
    name: "이노",
    gender: "남",
    age: "29",
    race: "거대우주햄스터",
    className: "마법사",
    group: "교사",
    info: "ESTJ·1w2·질서선·꼰대·츤데레" + "\n\n" + "베이지색 머리·금안·햄스터귀/꼬리·검은망토·앳된 외모·작은 키",
    physical: 40,
    defense: 40,
    magic: 71,
    imageUrl: "",
  },
];

export const worldSettings: WorldSetting[] = [
  {
    title: "연합국 수도 센트럴",
    content: [
      "다종족 도시. 경범죄부터 거대 재해까지 온갖 사건이 끊이지 않으나 시민들은 익숙하다.",
      "과거, 마왕을 토벌한 용사 가문은 대대로 내려져 오는 마왕의 저주를 받았다.",
      "마왕 토벌 후 기술이 급속도로 발달하였으며, 계급제가 폐지되고 현대화가 이루어졌다."
    ]
  },
  {
    title: "센트럴 기숙 학원",
    content: [
      "센트럴에 위치한, 취업용 전투력 향상 기숙학원이다.",
      "엘리트반 / 상급반 / 중급반 / 초급반으로 나뉜다.",
      "학년 없이 반만 구분되며, 차별 없이 대우는 동일하고 교실, 수업내용, 훈련강도만 다르다."
    ]
  },
  {
    title: "전투 시뮬레이션",
    content: [
      "전투 훈련용 가상공간. 특수 기기를 착용하여 입장한다.",
      "전투력을 스탯화해 옮겨 현실 전투를 완벽히 재현한다. 현실 전투력과 무관하게 등록 스탯이 적용되며, 현실과 동일하게 맞추는 것이 원칙이다.",
      "내부에서도 부상과 고통이 존재하나 현실 신체에는 영향이 없다.",
      "세팅 배경은 보통 도시 한복판이다."
    ]
  },
  {
    title: "스탯 시스템",
    content: [
      "전투력 수치화: 물리력(힘·파괴력) / 방어력(육체 내구도·파괴 저항) / 마력(마법 파괴력·효과 강도·지속성, 치유사는 회복량·속도)",
      "보편화된 개념은 아니며 취업학원에만 존재하는 시스템이다.",
      "범위: 0~20 연약함 | ~40 일반인 | ~60 숙련자 | ~80 초인 | ~90 재해 | ~100 규격 외",
      "순수 피지컬이 아니더라도 기교로 인해 스탯 증가가 가능하다."
    ]
  },
  {
    title: "승급 조건",
    content: [
      "엘리트반: 스탯 1개 이상 60 이상, 총합 120 이상 (바로 취직하여 현장에 투입될 수 있는 수준)",
      "상급반: 스탯 1개 이상 50 이상, 총합 100 이상",
      "중급반: 스탯 1개 이상 40 이상, 총합 80 이상",
      "초급반: 그 이하 (일반인이 전투를 배우러 온 수준)"
    ]
  }
];

export const schedules = [
  { date: "상시", event: "기본 일정", description: "이벤트가 없는 날은 오전 훈련, 오후 이론수업을 진행합니다." },
  { date: "매주 금요일", event: "경쟁 훈련", description: "파티 결성 가능, 파티 vs 파티 경쟁 훈련입니다. (던전이나 마수 토벌 아님)" },
  { date: "2월 28일", event: "입학식", description: "OT 및 시뮬레이션 전투결과로 반배정이 이루어집니다." },
  { date: "3월 20일", event: "단체 봄나들이", description: "봄맞이 단체 외출 일정입니다." },
  { date: "4월 20일", event: "중간모의평가", description: "가상 재해급 마물 토벌 실습이 진행됩니다." },
  { date: "5월 15일", event: "학원 교류전", description: "타학원 대항전으로, 파티 결성이 가능합니다." },
  { date: "6월 20일", event: "교류의 날", description: "연애적 호감있는 학생에게 선물을 주는 날입니다. (발렌타인데이 느낌)" },
  { date: "7월 15일", event: "단체 해변 휴가", description: "2박 3일간 해변으로 단체 휴가를 떠납니다." },
  { date: "8월 20일", event: "기말모의평가", description: "가상 기지 방어전이 진행되며 파티 결성이 가능합니다." },
  { date: "9월 20일", event: "전체 경쟁 훈련", description: "배틀로얄 형식으로 진행됩니다." },
  { date: "10월 20일", event: "학원축제", description: "공연 및 무도회가 열립니다." },
  { date: "11월 5일", event: "대축제", description: "마왕토벌 기념일로 전국적인 축제가 열립니다." },
  { date: "12월 20일", event: "승급전", description: "교사와 1:1 대련을 통해 승급 심사를 봅니다." },
  { date: "12월 31일", event: "졸업식", description: "성적에 상관없이 자유 졸업이 가능합니다." }
];
